<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $initialStock = rand(20, 100);

        Product::insert([
            [
                'name' => 'Kaos Kaki Polos Hitam',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki',
                'price' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Polos Putih',
                'image' => null,
                'color' => 'Putih',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki',
                'price' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Polos Abu-abu',
                'image' => null,
                'color' => 'Abu-abu',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki',
                'price' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sport Ankle Hitam',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sport',
                'price' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sport Ankle Putih',
                'image' => null,
                'color' => 'Putih',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sport',
                'price' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sport Panjang',
                'image' => null,
                'color' => 'Abu-abu',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sport',
                'price' => 22000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sekolah Putih',
                'image' => null,
                'color' => 'Putih',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sekolah',
                'price' => 18000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sekolah Hitam',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sekolah',
                'price' => 18000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Sekolah Panjang',
                'image' => null,
                'color' => 'Putih',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Sekolah',
                'price' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Casual Motif Garis',
                'image' => null,
                'color' => 'Multicolor',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Casual',
                'price' => 22000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Casual Motif Polkadot',
                'image' => null,
                'color' => 'Multicolor',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Casual',
                'price' => 23000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Casual Motif Stripe',
                'image' => null,
                'color' => 'Multicolor',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Casual',
                'price' => 23000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Kantor Hitam',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Formal',
                'price' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Kantor Abu-abu',
                'image' => null,
                'color' => 'Abu-abu',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Formal',
                'price' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Kantor Navy',
                'image' => null,
                'color' => 'Navy',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Formal',
                'price' => 21000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Anak Motif Kartun',
                'image' => null,
                'color' => 'Multicolor',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Anak',
                'price' => 17000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Anak Polos',
                'image' => null,
                'color' => 'Putih',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Anak',
                'price' => 16000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Anti Slip',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Fungsional',
                'price' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Thermal',
                'image' => null,
                'color' => 'Hitam',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Fungsional',
                'price' => 30000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaos Kaki Outdoor Tebal',
                'image' => null,
                'color' => 'Coklat',
                'category' => 'Pakaian',
                'type' => 'Kaos Kaki Outdoor',
                'price' => 28000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
